Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2021-12, with the labels that each got.

#142 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-142

#143 update-log4j
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-143

#144 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-144

#145 CCD-2231: Updated CVE suppression dates
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-145

#146 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-146
