Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2021-11, with the labels that each got.

#133 CCD-2120: Address CVE-2021-42340
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-133

#134 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-134

#135 CCD-2143: Address CVE-2021-22096
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-135

#136 Update Jenkinsfile_CNP sync branches
  Jenkinsfile_CNP
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-136

#138 CCD-2107: Update CVE suppression dates
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-138
