Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2021-08, with the labels that each got.

#125 CCD-1739 - Allow Family Private Law
  charts/cpo-case-payment-orders-api/Chart.yaml
  charts/cpo-case-payment-orders-api/values.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-125

#126 Suppress CVE-2021-28170
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-126

#127 Suppress CVE-2020-23171
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-127

#128 Resolve CVE-2021-22119 & CVE-2021-28170
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-128
