Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2021-07, with the labels that each got.

#114 suppress CVE
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-114

#115 fix for CVE-2021-27568
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-115

#118 fix for CVE-2021-30639
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-118

#117 CCD-1576: Integrate Fortify Scan into Nightly Pipelines
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-117

#120 fix for Fortify Issue 14727908-14727909 Null Dereference
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/cpo/controllers/CasePaymentOrdersControllerIT.java
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-120

#123 CPO-58: Add flag to control Rest API endpoints
  charts/cpo-case-payment-orders-api/Chart.yaml
  src/main/java/uk/gov/hmcts/reform/cpo/controllers/CasePaymentOrdersController.java
  src/main/resources/application.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-123
