Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-05, with the labels that each got.

#172 package update for CVE-2022-21724
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-172

#173 CCD-3111: Updated spring-framework.version to 5.3.19, removed suppression for CVE-2022-22968
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-173

#175 suppression of CVE-2016-1000027 and until date extension for current …
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-175

#176 suppression of CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-176

#177 suppression of CVE-2022-22970,CVE-2022-22971
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-177

#180 CCD-3293: Removed suppressions and updated spring-framework.version to 5.3.20
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-180

#181 CCD-3259 Fortify Issue 24259071 - Dockerfile Misconfiguration: Defaul…
  Dockerfile
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-181
