Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-08, with the labels that each got.

#202 CCD-3607: Temporarily suppress CVE-2022-31197
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-202

#203 CCD-3607: CVE-2022-31197 - Upgraded org.postgresql to 42.4.1 and removed temp suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-203

#204 Add backstage configuration file
  catalog-info.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-204
