Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-01, with the labels that each got.

#148 Amending suppression dates by 1 month
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-148

#147 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-147

#149 Update to build.gradle
  Jenkinsfile_CNP
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-149
