Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-06, with the labels that each got.

#182 CCD-3284: Add ARGs for builder stage paths to Dockerfile
  Dockerfile
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-182

#183 CCD-3387 Remove CVE Suppress Until Date from All Services
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-183

#179 CVE-2022-29885: cpo-case-payment-orders-api fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-179

#184 CCD-3248 Monthly Review of All Security Flags - Commented out all sup…
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-184

#187 Update suppressions.xml added temporary suppression for CVE-2022-34305
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-187
