Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-12, with the labels that each got.

#221 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-221

#223 CCD-4047-Fix-CVE-2022-41946
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-223

#225 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped java v…
  charts/cpo-case-payment-orders-api/Chart.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-225

#224 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-224
