Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-07, with the labels that each got.

#189 CCD-3450 : Update suppressions.xml (CVE-2022-33915)
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-189

#191 CCD-3450: CVE-2022-33915 cpo-case-payment-orders-api
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-191

#165 CCD-2496 Update all repos with multi arch base images
  Dockerfile
  acb.tpl.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-165

#188 CCD-965: Remove Temporary Sonar Exclusions cpo-case-payment-orders-api
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-188

#194 CCD-3536: CVE-2022-31569 suppress
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-194

#197 CCD-3512: Fix for CVE-2022-22969
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-197

#198 CCD-3515 CVE-2022-22976 Reduced not removed vulnerability, spring-sec…
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-198

#195 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/cpo-case-payment-orders-api/Chart.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-195

#192 CCD-3504 Upgrade to latest java plugin - java plugin upgraded to 0.12…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-192
