Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-04, with the labels that each got.

#162 Bump Spring framework to 5.3.18
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-162

#164 jackson.version update for CVE-2020-36518
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-164

#166 New Dates
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-166

#156 CWE 862
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/cpo/controllers/BaseMvcAuthChecks.java
  src/integrationTest/java/uk/gov/hmcts/reform/cpo/wiremock/extension/DynamicOAuthJwkSetResponseTransformer.java
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-156

#168 Hotfix for jackson dependency issue
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-168
