Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-09, with the labels that each got.

#207 Suppress CVE-2022-25857 in suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-207

#206 Ccd 3577 cleanup CVE suppressions
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-206

#208 CCD-3433 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-208

#210 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-210

#205 CCD-3649: Fix preview deploy issues
  Jenkinsfile_CNP
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-205

#200 CCD-3509 CVE-2021-22044 springCloud version upgraded to 2021.0.3
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/functionalTest/java/uk/gov/hmcts/reform/cpo/befta/CaseIdGenerator.java
  src/integrationTest/java/uk/gov/hmcts/reform/cpo/utils/UIDService.java
  src/integrationTest/java/uk/gov/hmcts/reform/cpo/wiremock/WireMockTestConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cpo/config/SwaggerConfiguration.java
  src/main/resources/application.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-200

#196 CCD-3539: Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-196

#199 Remove Version Number
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-199
