Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2022-02, with the labels that each got.

#150 CCD-2543: Ignore Fortify scan results
  build.gradle
  config/fortify-client.properties
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-150

#151 CCD-2591: Suppress CVE pending investigation
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-151

#152 CVE fixes
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-152

#153 CWE-862 Suppression
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-153

#155 Amend Suppression Dates
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-155

#157 update helm version
  charts/cpo-case-payment-orders-api/Chart.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-157
