Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2023-05, with the labels that each got.

#244 CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-244

#246 CCD-4479 : Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-246

#247 CCD-4608 Update renovate.json
  .github/renovate.json
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-247

#250 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-250
