Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2023-01, with the labels that each got.

#226 CCD-4157: Suppress CVE
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-226

#227 CCD-4163 Bump rse-gradle-java-plugin
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, keep-helm, rel:cpo-case-payment-orders-api-pr-227

#229 Update Chart.yaml
  charts/cpo-case-payment-orders-api/Chart.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-229

#233 CCD-4283 Bump rse-gradle plugin to add dependency-check v8.0.2
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-233
