Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2023-11, with the labels that each got.

#242 CCD-4454 : CVE-2022-1471 Fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-242

#255 CCD-4771 : Fix CVE-2023-35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-255

#259 HMAN-602 : Add retries to manifest-create
  acb.tpl.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-259

#260 HMAN-602 : Add retries to all acb.tpl.yaml entries
  acb.tpl.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-260

#262 CCD-5066 : Fix broken master pipeline due to CVE clash between DBs
  .github/workflows/dependency-check.yml
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-262

#261 Remove keep step in acb entries
  acb.tpl.yaml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-261
