Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2023-03, with the labels that each got.

#238 CCD-4396 : Update .terraform-version
  infrastructure/.terraform-version
Labels: ns:cpo, prd:cpo, add-or-update, rel:cpo-case-payment-orders-api-pr-238

#240 update befta-fw version to 8.7.11
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-240

#241 CCD-4398 Upgrade dependencies to resolve CVE-2023-24998
  build.gradle
  charts/cpo-case-payment-orders-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-241
