Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2024-05, with the labels that each got.

#275 CCD-5198 Updated Spring version to resolve CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, aat/no-changes, rel:cpo-case-payment-orders-api-pr-275

#272 CCD-5201 Changed spring security to v 6.1.5 as it is the most recent sub versi…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-272

#281 DO NOT MERGE CCD-5272 Decomission v11 Postgres database
  infrastructure/main.tf
Labels: ns:cpo, prd:cpo, aat/destroy, prod/destroy, rel:cpo-case-payment-orders-api-pr-281

#282 Update state.tf fix TF build
  infrastructure/state.tf
Labels: ns:cpo, prd:cpo, aat/destroy, prod/destroy, rel:cpo-case-payment-orders-api-pr-282

#283 Update state.tf fix build
  infrastructure/state.tf
Labels: ns:cpo, prd:cpo, aat/destroy, prod/destroy, rel:cpo-case-payment-orders-api-pr-283

#284 Update state.tf
  infrastructure/state.tf
Labels: ns:cpo, prd:cpo, aat/destroy, prod/destroy, rel:cpo-case-payment-orders-api-pr-284

#285 Update state.tf
  infrastructure/state.tf
Labels: ns:cpo, prd:cpo, aat/destroy, prod/destroy, rel:cpo-case-payment-orders-api-pr-285

#287 Update main.tf
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:cpo, prd:cpo, aat/destroy, prod/destroy, rel:cpo-case-payment-orders-api-pr-287
