Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2024-02, with the labels that each got.

#265 Attempt to fix ApplicationInsights
  Dockerfile
  build.gradle
  charts/cpo-case-payment-orders-api/values.preview.template.yaml
  lib/applicationinsights.json
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-265

#264 CCD-5024 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-264

#268 Updated TF version to fix pipeline error
  infrastructure/.terraform-version
Labels: ns:cpo, prd:cpo, add-or-update, rel:cpo-case-payment-orders-api-pr-268
