Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2024-08, with the labels that each got.

#291 enable fortify failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-291

#293 Fix master
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:cpo, prd:cpo, aat/add-or-update, prod/add-or-update, rel:cpo-case-payment-orders-api-pr-293

#294 CCD-5159:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-294

#288 CCD-5518 : Fix-CVE-2024-1597
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-288

#295 Revert ccd 5159
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-295

#296 Fix master tf
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:cpo, prd:cpo, aat/no-changes, prod/no-changes, rel:cpo-case-payment-orders-api-pr-296
