Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2024-03, with the labels that each got.

#266 Changes to resolve CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-266

#270 Fix CVE-2023-34034 : bump spring-security.version to 6.1.2
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-270

#271 Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 10.1.13
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-271
