Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2024-11, with the labels that each got.

#304 CCD-5953 : Fix-CVE-2023-52428
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-304

#298 CCD-4974:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-298

#305 CME-69: add java distro to workflow
  .github/workflows/swagger.yml
Labels: ns:cpo, prd:cpo, enable_keep_helm, rel:cpo-case-payment-orders-api-pr-305
