Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2025-05, with the labels that each got.

#319 CCD-6353 :: Suppressions for CVE-2025-31650, CVE-2025-31651
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-319

#321 cve_supression_cpo_case-payemnt
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-321

#316 CCD-5940 & CCD-6268:
  src/functionalTest/java/uk/gov/hmcts/reform/cpo/befta/CasePaymentOrdersTestAutomationAdapter.java
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125.feature
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125_Test_Swagger_JSON_Base_Data.td.json
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125_Test_Swagger_UI_Base_Data.td.json
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/S-125.1.td.json
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/S-125.2.td.json
  src/main/java/uk/gov/hmcts/reform/cpo/config/OpenApiConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cpo/config/SecurityConfiguration.java
Labels: ns:cpo, prd:cpo, keep-helm, aat/add-or-update, prod/add-or-update, enable_keep_helm, rel:cpo-case-payment-orders-api-pr-316
