Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2025-01, with the labels that each got.

#306 CME-316: Update azurerm
  infrastructure/state.tf
Labels: ns:cpo, prd:cpo, aat/no-changes, prod/no-changes, rel:cpo-case-payment-orders-api-pr-306

#307 CCD-6049 : Bump ccd-test-definitions and befta-fw to latest
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/cpo/befta/CasePaymentOrdersBeftaRunner.java
Labels: ns:cpo, prd:cpo

#299 CCD-5313:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-299
