Repository hmcts/cpo-case-payment-orders-api, pull requests merged in 2025-06, with the labels that each got.

#326 CCD-6389 tidy up
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-326

#329 CCD-6489 :: suppress CVE 2024 22259
  config/owasp/suppressions.xml
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-329

#324 CME-599 bump versions to address CVEs
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/integrationTest/java/uk/gov/hmcts/reform/cpo/wiremock/WireMockTestConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cpo/config/OpenApiConfiguration.java
Labels: ns:cpo, prd:cpo, rel:cpo-case-payment-orders-api-pr-324
